In [30]:
# Date: 26/11/2023
# CSC461 – Assignment3 – Machine Learning
# FA21-BSE-053
# Usama Tufail


In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [18]:
df=pd.read_csv("gender-prediction.csv");

In [19]:
df['gender'].value_counts()

male      62
female    48
Name: gender, dtype: int64

In [20]:
labels = preprocessing.LabelEncoder()
df['beard'] = labels.fit_transform(df['beard'])
df['hair_length'] = labels.fit_transform(df['hair_length'])
df['eye_color'] = labels.fit_transform(df['eye_color'])
df['scarf'] = labels.fit_transform(df['scarf'])
df['gender'] = labels.fit_transform(df['gender'])


In [21]:
x = df.drop('gender', axis=1)
y = df['gender']

**Logistic Regression**

In [22]:
#Logistic Regression
X_train, x_test, Y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = 2,)
model = LogisticRegression()
model.fit(X_train, Y_train)
y_pred = model.predict(x_test)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)

Confusion Matrix:
[[14  0]
 [ 1 22]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      1.00      0.97        14
           1       1.00      0.96      0.98        23

    accuracy                           0.97        37
   macro avg       0.97      0.98      0.97        37
weighted avg       0.97      0.97      0.97        37



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


**Dropped 2 most important attributes**

In [23]:
#Dropped 2 most important attributes
x_droped=df.drop(['gender','scarf','shoe_size'],axis=1)
y_new=y
X_train, x_test, Y_train, y_test = train_test_split(x_droped, y, test_size = 0.20, random_state = 42,)
model = MLPClassifier()
model.fit(X_train, Y_train)
y_pred = model.predict(x_test)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)

Confusion Matrix:
[[ 0 12]
 [ 0 10]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        12
           1       0.45      1.00      0.62        10

    accuracy                           0.45        22
   macro avg       0.23      0.50      0.31        22
weighted avg       0.21      0.45      0.28        22



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**Check most important input attributes**

In [24]:
# Check most important input attributes
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
X = df.drop('gender', axis=1)
y = df['gender']
model = RandomForestRegressor()
model.fit(X, y)
feature_importances = model.feature_importances_
feature_importance_df = pd.DataFrame({'Feature': X.columns, 'Importance': feature_importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
print(feature_importance_df)


       Feature  Importance
4    shoe_size    0.706040
5        scarf    0.116666
2        beard    0.092683
0       height    0.069685
1       weight    0.009004
3  hair_length    0.004638
6    eye_color    0.001285


**Support vector machines**

In [25]:
# Support vector machines
X_train, x_test, Y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 2,)
model = LinearSVC()
model.fit(X_train, Y_train)
y_pred = model.predict(x_test)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)


Confusion Matrix:
[[9 0]
 [9 4]]
Classification Report:
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         9
           1       1.00      0.31      0.47        13

    accuracy                           0.59        22
   macro avg       0.75      0.65      0.57        22
weighted avg       0.80      0.59      0.55        22



/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


**Multilayer Perceptron classification**

In [26]:

X_train, x_test, Y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 2)
model = MLPClassifier()
model.fit(X_train, Y_train)
y_pred = model.predict(x_test)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)


Confusion Matrix:
[[ 8  1]
 [ 2 11]]
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.89      0.84         9
           1       0.92      0.85      0.88        13

    accuracy                           0.86        22
   macro avg       0.86      0.87      0.86        22
weighted avg       0.87      0.86      0.86        22



/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


**Monte Carlo cross-validation** and **Leave P-Out cross-validation**

In [27]:
def monte_carlo_cross_validation(model, X, y, iterations=100):
    f1_scores = []
    for _ in range(iterations):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, )
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        f1_scores.append(f1_score(y_test, y_pred, ))
    return np.mean(f1_scores)
def leave_p_out_cross_validation(model, X, y, p=5):
    fold = StratifiedKFold(n_splits=p)
    f1_scores = []
    for train, test in fold.split(X, y):
        X_train, X_test = X.iloc[train], X.iloc[test]
        y_train, y_test = y.iloc[train], y.iloc[test]
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        f1_scores.append(f1_score(y_test, y_pred,))
    return np.mean(f1_scores)

rf_classifier = RandomForestClassifier(random_state=42)
monte_carlo_f1 = monte_carlo_cross_validation(rf_classifier, X, y)
leave_p_out_f1 = leave_p_out_cross_validation(rf_classifier, X, y, p=4)
print(f'Monte Carlo Cross-Validation F1 Score: {monte_carlo_f1:.4f}')
print(f'Leave P-Out Cross-Validation F1 Score: {leave_p_out_f1:.4f}')


Monte Carlo Cross-Validation F1 Score: 0.9786
Leave P-Out Cross-Validation F1 Score: 0.9838


**Question 4**

In [28]:
X_train = df.drop('gender', axis=1)
Y_train=df['gender']
df_test=pd.read_csv("New_data.csv");
labels = preprocessing.LabelEncoder()
df_test['beard'] = labels.fit_transform(df_test['beard'])
df_test['hair_length'] = labels.fit_transform(df_test['hair_length'])
df_test['eye_color'] = labels.fit_transform(df_test['eye_color'])
df_test['scarf'] = labels.fit_transform(df_test['scarf'])
df_test['gender'] = labels.fit_transform(df_test['gender'])
x_test = df_test.drop('gender', axis=1)
y_test =df_test['gender']

**Gaussian Naïve Bayes classification**

In [29]:

model = GaussianNB()
model.fit(X_train, Y_train)
y_pred = model.predict(x_test)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)



Accuracy: 1.00
Confusion Matrix:
[[4 0]
 [0 6]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         6

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10

